### ISSUE TITLE
Linux build and run errors

### ISSUE THREAD

**Issue by omid** [markrai/gitpow#3]
On my Linux I faced this issue:
```
failed to bundle project `failed to run linuxdeploy`
```
I think it's for building "AppImage". I got the same error, even after I installed `linuxdeploy`.

Anyway, I run the binary from `target/release/gitpow-tauri` then I got this error:
```
Gdk-Message: 13:15:20.698: Error 71 (Protocol error) dispatching to Wayland display.
```

**Comment by omid** [comment]
Hello,

Nope. Not fixed. I still see the first error.

And having a Linux on a virtual machine is pretty easy.

**Comment by markrai** [comment]
Thanks for checking! I was actually running out of hard disk space, so I was reluctant to install Linux. I'll be getting a larger hard drive this afternoon, and then I'll be able to test properly.

**Comment by markrai** [comment]
Hi @omid - I just pushed out a test script for Linux: test-linux-build.sh
I tested it on Ubuntu. Please give it a try :)

**Comment by omid** [comment]
Nope.
Still the same error:

```
Bundling GitPow_0.1.2_amd64.AppImage (./gitpow/target/release/bundle/appimage/GitPow_0.1.2_amd64.AppImage)
       Error failed to bundle project `failed to run linuxdeploy`
```

Just if it's important, I'm on Arch.
